@url_dev= http://127.0.0.1:3055/v1/api/



### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 56904024af493dfc60972f0c8d701133398fb199d868f330bffd83ab52f39eccc8c70d9b81658eaacd620252b5b7f17e5266ca34aae492e0545590130bd2aa69
x-client-id: 66f9505e0cf833958071fc06
authorization:yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY5NTA1ZTBjZjgzMzk1ODA3MWZjMDYiLCJlbWFpbCI6InNob3B0aXBqczAyQGdtYWlsLmNvbSIsImlhdCI6MTcyNzYxNTA5NiwiZXhwIjoxNzI4MjE5ODk2fQ.jS_z2m8RvwFIpbGdyK3AffiUjeXjjmCVYh3ajxkheD8

{
        "email": "shoptipjs02@gmail.com",
        "password": "abc123"
}

